### ISSUE TITLE
Package development: Example Projects don't get a working language server / code actions

### ISSUE THREAD

**Issue by dkbast** [iamcco/coc-flutter#134]
**Describe the bug**
I am developing a new Flutter package - when I'm in package_name/lib everything works as expected, but when I'm writing the examples in package_name/example/lib/main.dart I don't get any code actions or language server features.

**To Reproduce**
1. For reference go to https://flutter.dev/docs/development/packages-and-plugins/developing-packages
2. Create a package like os: flutter create --template=package hello
3. Create a new folder 'example' and run flutter create .
4. vim example/lib/main.dart

**Expected behavior**
I can develop the example using all the features I usually have - It would be ok if I would need two different sessions for developing the example and the package - the entry point could determine where the language server should start.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Vim or Neovim: Neovim
 - (Neo)vim version: NVIM v0.5.0

**Config**
If you have any config for this specific extenstion in you `coc-settings` please include them here.
```
{
  "languageserver": {
    "dart": {
      "command": "dart_language_server",
      "args": [],
      "filetypes": ["dart"],
      "initializationOptions": {},
      "settings": {
        "dart": {
          "validation": {},
          "completion": {}
        }
      }
    }
  }
}
```

**Comment by Kavantix** [comment]
Can you try opening the project from the example directory itself.
Also, you should not need the part in ‘coc-settings`, coc-flutter handles that

**Comment by dkbast** [comment]
There seems to be no difference between `vim example/lib/main.dart` and `cd example` `vim lib/main.dart`

In both cases I get '[coc.nvim] No code action available' and no analyzer, closing tags etc pp

The path within vim is displayed as 'example/lib/main.dart' no matter from where I start - so I guess there is some magic going on in discovering which kind of project I'm working on and to auto discover other files and folders?

**Comment by changyiyao** [comment]
try setting `flutter.lsp.initialization.onlyAnalyzeProjectsWithOpenFiles` to `false`

**Comment by dkbast** [comment]
@changyiyao I tried, but this didn't work for me - did you give it a try? Does it work for you?

**Comment by changyiyao** [comment]
@dkbast Have the similar issue but workaround well as the following:
1. make the package be the local dependency of the example project, you may configure like ../ on dependency_overrides to the pubspec of example.

2. cd to example dir.

3. vim/nvim

4. `:e lib/main.dart` (In my experience it must firstly open one dart file which belongs to example project, otherwise the lsp doesn't work well for dart files of example project if you open a dart file of package project at once)

5. At last, with cocconfig I mentioned above, you will see the lsp works both in example and package project.

**Comment by Kavantix** [comment]
@dkbast can you check if v1.9.6 fixed your issue?

**Comment by changyiyao** [comment]
> @dkbast Have the similar issue but workaround well as the following:
> 
> 1. make the package be the local dependency of the example project, you may configure like ../ on dependency_overrides to the pubspec of example.
> 2. cd to example dir in your terminal emulator.
> 3. open vim/nvim editor without args.
> 4. `:e lib/main.dart` (In my experience it must firstly open one dart file which belongs to example project, otherwise the lsp doesn't work well for dart files of example project if you open a dart file of package project at once)
> 5. At last, with cocconfig I mentioned above, you will see the lsp works both in example and package project.

Finally, I found another way to work properly without `cd` into the `example` folder:
 **Background**:
 Since default rootPatterns of workspace when you open dart files is like:
 {"global": [".git", ".hg", ".projections.json"], "buffer": [], "server": ["pubspec.yaml"]}
Coc.nvim recognize workspaces by this patterns when you once open a file. 
By default, when opening example/lib/main.dart from package project root path, Coc use up-bottom mode to specify the workspace, which only treats the package project root path as the workspace rather than the example folder, which causes commands such as `flutter.run` cannot found the entry lib/main.dart file, even though you append args `-t example/lib/main.dart`.
To solve the issue, set workspace.bottomUpFiletypes, such as 
```json
{
  ...
  "workspace.bottomUpFiletypes": ["dart", "yaml"],
  ...
}
```

**Comment by dkbast** [comment]
Sorry for not being very responsive on this issue - today I opened up another package and it looks like this problem does not exist anymore. @Kavantix looks like this is fixed without needing any configuration. Thanks!

For others wondering if this is working, I've just checked out https://github.com/trufi-association/trufi-core and and can confirm that I can work in the package as well as in the example directory, at least at first glance I didn't run into any issues.
