### ISSUE TITLE
Flutter app errors cause: error nvim_win_get_buf - Invalid window id: 1753

### ISSUE THREAD

**Issue by Akin909** [iamcco/coc-flutter#44]
**Describe the bug**
When I'm developing a flutter app using `coc-flutter` with `openDevLog` (not sure if this is necessary)
a bunch of floating windows are opened with the error messages, these quickly fill the screen as several windows are opened. When these windows begin to close I then get

```
[coc.nvim]: UnhandledRejection: request error nvim_win_get_buf - Invalid window id: 1756                                                                              
Error: request error nvim_win_get_buf - Invalid window id: 1756                                                                                                       
    at /home/akin/.local/share/nvim/plugged/coc.nvim/build/index.js:15213:32                                                                                          
    at /home/akin/.local/share/nvim/plugged/coc.nvim/build/index.js:11878:13                                                                                          
    at NvimTransport.parseMessage (/home/akin/.local/share/nvim/plugged/coc.nvim/build/index.js:11819:17)                                                             
    at DecodeStream.<anonymous> (/home/akin/.local/share/nvim/plugged/coc.nvim/build/index.js:11789:18)                                                               
    at DecodeStream.emit (events.js:311:20)                                                                                                                           
    at addChunk (_stream_readable.js:294:12)                                                                                                                          
    at readableAddChunk (_stream_readable.js:275:11)                                                                                                                  
    at DecodeStream.Readable.push (_stream_readable.js:209:10)                                                                                                        
    at DecodeStream.Transform.push (_stream_transform.js:152:32)                                                                                                      
    at DecodeBuffer.DecodeStream.decoder.push (/home/akin/.local/share/nvim/plugged/coc.nvim/build/index.js:14761:12) 
```

**To Reproduce**
1. Open a simple flutter app that throws many exceptions or exceptions in a loop
2. run the app (I'm using an android emulator)
2. Several error windows appear, eventually nvim starts throwing window id errors

**Expected behavior**
Ideally there would only be one floating window and I can scroll the contents or just says you app threw and exception check the logs, if that's not possible tbh I'd rather have no windows and I can check the dev log myself

**Screenshots**
![coc-flutter-error](https://user-images.githubusercontent.com/22454918/86126559-6d6f4d80-bad6-11ea-93e1-6b2f0b7bf36e.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Vim or Neovim: Neovim
 - (Neo)vim version: Nightly

**Comment by theniceboy** [comment]
[Same issue here](https://github.com/neoclide/coc.nvim/issues/2113)

**Comment by iamcco** [comment]
I had remove floating window notification for dev log. since it's not make sense when display too much message.

**Comment by Chidhambararajan** [comment]
I too had this issue , looks like this issue shows up only when running log intensive applications like an embedded Webview or a video player in a flutter application

```
[coc.nvim] error: UnhandledRejection: request error nvim_win_get_buf - Invalid window id
Error: request error nvim_win_get_buf - Invalid window id
    at /home/captain-america/.config/nvim/plugged/coc.nvim/build/index.js:15194:32
    at /home/captain-america/.config/nvim/plugged/coc.nvim/build/index.js:11864:13
    at NvimTransport.parseMessage (/home/captain-america/.config/nvim/plugged/coc.nvim/build/index.js:11805:17)
    at DecodeStream.<anonymous> (/home/captain-america/.config/nvim/plugged/coc.nvim/build/index.js:11775:18)
    at DecodeStream.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at DecodeStream.Readable.push (_stream_readable.js:224:10)
    at DecodeStream.Transform.push (_stream_transform.js:150:32)
    at DecodeBuffer.DecodeStream.decoder.push (/home/captain-america/.config/nvim/plugged/coc.nvim/build/index.js:14742:12)
```

**Comment by iamcco** [comment]
@Chidhambararajan 

> Is it only due to the floating dev log?

Yes.

I don't have much time to deal with this issue, it maybe an option to enabled floating notification in the future if I have time to do it.

**Comment by Akin909** [comment]
Thanks @iamcco that's super helpful since at least I can work without the error messages 👍 If you have an idea of how to implement this without the erroring maybe you can write how you would do it and if I get time next week I can have a look

**Comment by theniceboy** [comment]
Hey @akinsho, this issue was fixed in [my fork of `coc-flutter`](https://github.com/theniceboy/coc-flutter), and I've published it on [npm](https://www.npmjs.com/package/coc-flutter-tools). You can install it with `:CocInstall coc-flutter-tools` (but make sure you do `:CocUninstall coc-flutter` if you do that). I was thinking about submitting a PR but turns out that the author uses spaces instead of tabs and my fork use tabs instead of spaces lol. I will be actively fixing bugs and adding new features, and I'll be pulling code from this repo as well. Big thanks to the original author for creating `coc-flutter`! It has helped me a lot, but it seems like the author doesn't have too much time for now to maintain this plugin.

**Comment by akinsho** [comment]
@theniceboy cool to see the issue fixed, re. tabs v spaces being a blocker to submitting a PR surely you can do a search and replace or something to switch for tabs to spaces etc? 🤷🏿‍♂️ .

**Comment by akinsho** [comment]
It's entirely up to you in the end since OSS, but there are probably already a lot of people using this package and @iamcco has created a lot of useful extensions/plugins which he's maintaining like `coc-vimlsp`, `coc-spell-checker` as well as `markdown-preview.nvim` (and a bunch more) so I'm sure he'd appreciate some help adding features to this one and it would benefit a lot of people rather than a new extension altogether

**Comment by theniceboy** [comment]
I completely agree with you, @akinsho. I'll submit a PR eventually. I've been thinking about some new features that I want to add. Some might be too aggressive like notification filtering. Here's another one that I've implemented:
![Screen Shot 2020-08-09 at 6 25 10 PM](https://user-images.githubusercontent.com/8187501/89730211-575a9280-da6f-11ea-9ad1-73770c1840db.png)
It shows the path of the UI component under the cursor. I'm not really sure that this is something that the author and the current userbase want. I greatly appreciate what the author has done and I'll submit a PR as soon as I get all the features I want to add stabilized. The author can then decide whether if he wants those features.

**Comment by akinsho** [comment]
The outline thing is really cool I don't think I could fit it into my statusline but saw this functionality recently in vscode. Which I think is based on the same thing. Seems like it might be a bit tough to create with `extmarks` in neovim which I'm not sure if those are done yet

![image](https://user-images.githubusercontent.com/22454918/89770170-499c2000-daf6-11ea-8c59-88e498b125e9.png)

I also saw it rendered in a tree in code which would be really cool.
I know there's an issue about adding a tree renderer to coc in general for things like this already

**Comment by theniceboy** [comment]
Yeah @akinsho, I was exploring options to add those lines and it seems impossible. The status bar thing is based on the same thing that those lines are dependent upon, but there's no way in (neo)vim to dynamically draw inline virtual text. I don't think extended marks can draw lines, and I don't think I can utilize `conceal` because `conceal` is based on syntax match. My status line was pretty empty so I thought I could make use of it a little bit. It turns out to work pretty well, and I think it's a pretty viable alternative to drawing those tree-like lines in code (as those lines can also make your code a little bit messy). I can also make a side panel that displays the widget tree if that sounds useful.
![Screen Shot 2020-08-10 at 5 55 23 PM](https://user-images.githubusercontent.com/8187501/89771308-addcd500-db32-11ea-8fdc-e94b806311a2.png)

**Comment by akinsho** [comment]
Yeah it seemed quite dicey at the time to implement in (n)vim but think there's been some talk on one of the issues or super early PRs in neovim to allow something like that maybe.

Either way I actually think the sidebar panel is more useful since it lets you see the full hierarchy of components at a glance. I think just visualizing it indented etc and maybe collapsible would be quite useful. I use a dev plugin for `nvim-treesitter` which renders a tree, [treesitter playground](https://github.com/nvim-treesitter/playground) which is a similar type of thing but maybe less fancy.

**Comment by theniceboy** [comment]
Hey @akinsho, I tried `nvim-treesitter` and my initial impressions are really good.... except it boosted my nvim startup time to about 10 seconds... I'm not sure why that happened but it seems like there are other people who have encountered the same issue. I'll keep an eye on this the treesitter progress though. It looks really cool!

Btw I've implemented a side panel that shows the flutter outline visually. I'll be testing it in my fork. Here's a preview:
![Flutter Outline](https://user-images.githubusercontent.com/8187501/90091803-eca0a400-dd59-11ea-9bee-2401c85ddff9.gif)

**Comment by akinsho** [comment]
😍 😍 I just tried it out, it's *very* cool 👏🏿 👏🏿

**Comment by akinsho** [comment]
Quick side note @theniceboy it would probably be worth making the panel `nobuflisted` and/or `bufhide=wipe` since atm the buffer is accessible in the buffer list which I don't think is useful since it's only relevant as a buffer local thing like `vista`.

**Comment by theniceboy** [comment]
@akinsho Good catch! I pushed a new version. I also made it so that the outline window will close when it becomes the last window in the current tab page.

**Comment by akinsho** [comment]
Nice quick work 💪🏿 , seems like it introduces a bug though. To reproduce open the outline, close it with `:q`, navigate to a new buffer.

![image](https://user-images.githubusercontent.com/22454918/90132065-0b586800-dd65-11ea-9167-02b04aa17b92.png)

Also I just noticed the buffer is `modifiable` so a user can accidentally change the text inside it 😨

**Comment by theniceboy** [comment]
That was kinda embarrassing haha. fixed

About the `modifiable` issue. In order for me to change this buffer, I have to set the buffer to be modifiable, modify it, and then set it to `nomodifiable` again. These increases lag slightly. I think it's ok if a user modifies the buffer accidentally because when you change the source file or switch to a new buffer, the outline buffer will be updated again. Please lmk if there's a better way than setting the buffer to modifiable or nomodifiable over and over again.

**Comment by akinsho** [comment]
Nice 👍🏿 that fixed it.

Tbh I think the standard for this kind of thing is to set to `modified` append then set to `nomodifiable`. This issue I'm describing though is that `nomodifiable` *is not set* at all. So the buffer is actually `modifiable` after I open it.

As an example I can type something at the bottom of the buffer and it will stay there even after I switch buffers and the outline is updated. I think a slight lag is fine if the payoff is that you can't accidentally corrupt the tree.

**Comment by theniceboy** [comment]
@akinsho That makes sense. I made the buffer to be unmodifiable. It doesn't add too much lag which is good. Also, the filetype is now flutterOutline.

**Comment by akinsho** [comment]
No noticeable lag @theniceboy works much better also it's not accidentally now creating files in my system since it can't be written to anymore 😆

**Comment by theniceboy** [comment]
> EDIT: it might also be work setting `winfixwidth` if a user (like myself) has `equalalways` (it is the **default** in nvim) on then when I close a split the outline buffer is resized to take up more space. Think a lot of panels like e.g. vista or peekabo do this. But alternatively if you don't want to lock users into a specific width then you can git the buffer a `&filetype` and then a user can do `autocmd FileType flutterOutline setlocal winfixwidth`

Yes! That is very helpful. I've also added the `flutter.toggleOutline` command and the `flutter.outlineWidth setting`. Please lmk if those are useful.

**Comment by akinsho** [comment]
The toggle is *very* useful I was moving into the split then running `:q` every time before 😆 , also fixing the width and giving an option 🚀 👍🏿
