### ISSUE TITLE
Would it be possible to add a command to open Dart DevTools in browser similar to openProfiler?

### ISSUE THREAD

**Issue by unknowledgeable** [iamcco/coc-flutter#54]
Maybe it's already implemented but I can't find it. Looking for a Coc command similar to flutter.dev.openProfiler that would run:

`pub global run devtools`

Then open a browser at:

http://127.0.0.1:9100/#/

but with the URL completed with the the current running profile in from flutter.dev.openProfiler to give something like:

http://127.0.0.1:9100/#/?uri=ws%XXXXXXXXXXXXXXXXXXX%2Fws

Would this be possible?

useful link: https://flutter.dev/docs/development/tools/devtools/cli

**Comment by theniceboy** [comment]
Funny thing, I thought of that yesterday as well. I made a [fork](https://github.com/theniceboy/coc-flutter) and [got it working](https://github.com/theniceboy/coc-flutter/commit/c2cb6d458dee433ab9c138c9742231679b147f86). Feel free to take the code but I probably won’t submit a PR because I’m gonna make some further changes (like really fixing #44). Either way, feel free to try out my fork, I’ll be actively maintaining this fork since I’m heavily depending on it.

To use my fork, put this in your vimrc:
```
set runtimepath^=/path/to/my/fork/of/coc-flutter
```

**Comment by unknowledgeable** [comment]
What a coincidence!

Please let me know if and when you do submit a PR. I'm very grateful for your suggestion but I'm only just getting to grips with vim/neovim and I'm in the (very confusing) process of building my vimrc/init.vim for the first time so would like to keep it as clean as possible. With my current level of experience, it seems everything I try to implement tends to break functionality somewhere else! I'd rather not start playing around with custom paths to forks else my machine might catch fire!

**Comment by theniceboy** [comment]
Haha, I understand. @unknowledgeable  I might submit a PR after I fix everything. I might also submit my fork as an npm package so that you'll be able to install it with whatever method you were using to install `coc-flutter`.

**Comment by theniceboy** [comment]
Hey @unknowledgeable , I published [my fork](https://github.com/theniceboy/coc-flutter) on [npm](https://www.npmjs.com/package/coc-flutter-tools). You can install it with `:CocInstall coc-flutter-tools` (but make sure you do `:CocUninstall coc-flutter` if you do that). I was thinking about submitting a PR but turns out that the author uses spaces instead of tabs and my fork use tabs instead of spaces lol. I will be actively fixing bugs and adding new features, and I'll be pulling code from this repo as well. Big thanks to @iamcco for creating `coc-flutter`! It has helped me a lot, but it seems like the author doesn't have too much time for now to maintain this plugin.

**Comment by unknowledgeable** [comment]
@theniceboy that's great news! Will have a play around with it later today and see how it goes!

**Comment by theniceboy** [comment]
@unknowledgeable Thanks! Btw please also try out this cool new feature I added! It should be enabled by default. (Might be related to #10)
![Screen Shot 2020-08-09 at 6 25 10 PM](https://user-images.githubusercontent.com/8187501/89730211-575a9280-da6f-11ea-9ad1-73770c1840db.png)

**Comment by unknowledgeable** [comment]
@theniceboy opening devtools works great! Love the new feature too, very handy! Thanks!

**Comment by iamcco** [comment]
This should be support by https://github.com/iamcco/coc-flutter/pull/61
